# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023-2024 Anna <cyber@sysrq.in>

[tool.bumpversion]
current_version = "1.1.4"
commit = true
tag = true
tag_name = "{new_version}"
tag_message = "Release {new_version}"
sign_tags = true

[[tool.bumpversion.files]]
filename = "nimbus.nimble"

[[tool.bumpversion.files]]
filename = "src/nimbs/common.nim"

[[tool.bumpversion.files]]
filename = "docs/conf.py"

[[tool.bumpversion.files]]
filename = "docs/release-notes.rst"
search = "{current_version}-next"
replace = "{new_version}"
