# SPDX-FileCopyrightText: 2023 Anna <cyber@sysrq.in>
# SPDX-License-Identifier: BSD-3-Clause

kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: nimlang/nim:latest-alpine
    commands:
      - nimble test

---
kind: pipeline
type: docker
name: sphinx-doc
steps:
  - name: build
    image: sphinxdoc/sphinx:latest
    commands:
      - pip install -r docs/requirements.txt
      - sphinx-build docs docs/_build

---
kind: pipeline
type: docker
name: reuse-lint

steps:
  - name: lint
    image: fsfe/reuse:latest
    commands:
      - reuse lint
