---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: nimlang/nim:alpine
    commands:
      - testament --megatest:off all

  - name: sphinx-doc
    image: sphinxdoc/sphinx:latest
    commands:
      - pip install -r docs/requirements.txt
      - sphinx-build docs docs/_build
